package com.mycompany.osapp3.entity;
// Generated 10/nov/2018 12:25:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,schema="public"
)
public class Employee  implements java.io.Serializable {


     private int id;
     private String name;
     private Date startDate;
     private Set<Platoon> platoons = new HashSet<Platoon>(0);
     private Set<Role> roles = new HashSet<Role>(0);
     private Set<EmployeeProject> employeeProjects = new HashSet<EmployeeProject>(0);

    public Employee() {
    }

	
    public Employee(int id, String name, Date startDate) {
        this.id = id;
        this.name = name;
        this.startDate = startDate;
    }
    public Employee(int id, String name, Date startDate, Set<Platoon> platoons, Set<Role> roles, Set<EmployeeProject> employeeProjects) {
       this.id = id;
       this.name = name;
       this.startDate = startDate;
       this.platoons = platoons;
       this.roles = roles;
       this.employeeProjects = employeeProjects;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=13)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Platoon> getPlatoons() {
        return this.platoons;
    }
    
    public void setPlatoons(Set<Platoon> platoons) {
        this.platoons = platoons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<EmployeeProject> getEmployeeProjects() {
        return this.employeeProjects;
    }
    
    public void setEmployeeProjects(Set<EmployeeProject> employeeProjects) {
        this.employeeProjects = employeeProjects;
    }




}


