package com.mycompany.osapp3.entity;
// Generated 10/nov/2018 23:35:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeProjectId generated by hbm2java
 */
@Embeddable
public class EmployeeProjectId  implements java.io.Serializable {


     private int employeeId;
     private int projectId;

    public EmployeeProjectId() {
    }

    public EmployeeProjectId(int employeeId, int projectId) {
       this.employeeId = employeeId;
       this.projectId = projectId;
    }
   


    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployeeProjectId) ) return false;
		 EmployeeProjectId castOther = ( EmployeeProjectId ) other; 
         
		 return (this.getEmployeeId()==castOther.getEmployeeId())
 && (this.getProjectId()==castOther.getProjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmployeeId();
         result = 37 * result + this.getProjectId();
         return result;
   }   


}


