package com.mycompany.osapp3.entity;
// Generated 10/nov/2018 12:25:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Platoon generated by hbm2java
 */
@Entity
@Table(name="platoon"
    ,schema="public"
)
public class Platoon  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private String role;

    public Platoon() {
    }

    public Platoon(int id, Employee employee, String role) {
       this.id = id;
       this.employee = employee;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="role", nullable=false)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


